"""Add Performance model for content analytics

Revision ID: 0b89c643b9a5
Revises: 7b8fd20167ab
Create Date: 2025-10-29 17:49:46.027034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b89c643b9a5'
down_revision: Union[str, Sequence[str], None] = '7b8fd20167ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True, comment='세그먼트 이름 (예: MZ세대 뷰티 관심자)'),
    sa.Column('filter_conditions', sa.JSON(), nullable=False, comment='필터 조건 (age_group, gender, interests 등)'),
    sa.Column('cached_profile_ids', sa.JSON(), nullable=False, comment='매칭된 Target 프로필 ID 목록'),
    sa.Column('profile_count', sa.Integer(), nullable=False, comment='매칭된 프로필 수'),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True, comment='마지막 접근 시간'),
    sa.Column('access_count', sa.Integer(), nullable=True, comment='접근 횟수'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_index(op.f('ix_segments_name'), 'segments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_name'), table_name='segments')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_table('segments')
    # ### end Alembic commands ###
