"""Add product fields to Content table

Revision ID: 4d569c57b3eb
Revises: a218e7d53574
Create Date: 2025-11-04 15:55:46.982105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d569c57b3eb'
down_revision: Union[str, Sequence[str], None] = 'a218e7d53574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('product_name', sa.String(length=200), nullable=True))
    op.add_column('contents', sa.Column('product_description', sa.Text(), nullable=True))
    op.add_column('contents', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'category')
    op.drop_column('contents', 'product_description')
    op.drop_column('contents', 'product_name')
    # ### end Alembic commands ###
