"""add user_id to contents table

Revision ID: 74d410a5cae0
Revises: 4d569c57b3eb
Create Date: 2025-11-04 16:59:36.231822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d410a5cae0'
down_revision: Union[str, Sequence[str], None] = '4d569c57b3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add user_id column as nullable first
    op.add_column('contents', sa.Column('user_id', sa.Integer(), nullable=True))

    # Step 2: Set default user_id = 1 for existing contents (테스트 사용자)
    op.execute("UPDATE contents SET user_id = 1 WHERE user_id IS NULL")

    # Step 3: Make user_id NOT NULL
    op.alter_column('contents', 'user_id', nullable=False)

    # Step 4: Add foreign key constraint
    op.create_foreign_key(None, 'contents', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'user_id')
    # ### end Alembic commands ###
