"""Create performances table with all fields

Revision ID: a218e7d53574
Revises: 155d6db0813d
Create Date: 2025-10-29 18:36:14.602594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a218e7d53574'
down_revision: Union[str, Sequence[str], None] = '155d6db0813d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.Enum('AI_SIMULATION', 'REAL_DATA', name='datasource'), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('brand_recall_score', sa.Float(), nullable=True),
    sa.Column('target_breakdown', sa.JSON(), nullable=True),
    sa.Column('personas_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('campaign_start_date', sa.String(length=50), nullable=True),
    sa.Column('campaign_end_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_content_id'), 'performances', ['content_id'], unique=False)
    op.create_index(op.f('ix_performances_id'), 'performances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performances_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_content_id'), table_name='performances')
    op.drop_table('performances')
    # ### end Alembic commands ###
